version: '3'

networks:
  proxy:
    driver: bridge
    internal: true
  nextcloud:
    driver: bridge
    internal: true
  internet:
    driver: bridge

services:
  proxy:
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./npm_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - internet
      - proxy
      - nextcloud
    depends_on:
      - 'rp_db'

  rp_db:
    restart: always
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./rp_db:/var/lib/mysql
    networks:
      - proxy

  nextcloud:
    image: nextcloud:apache
    restart: always
    links: 
      - nc_db
      - redis
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
      - /ssdpool:/ssdpool # local external storage
    networks:
      - nextcloud

  nc_db:
    image: mariadb
    restart: always
    volumes:
      - ./nc_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_USER_PW}
    networks:
      - nextcloud

  redis:
    restart: always
    image: redis
    networks:
      - nextcloud

  collabora:
    restart: always
    image: collabora/code
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - domain=${DOMAIN}
    networks:
      - nextcloud
