version: '3'

networks:
  default:
    external:
      name: tinycloud-main

services:
  nextcloud:
    image: nextcloud:apache
    restart: always
    hostname: nextcloud
    links: 
      - nc_db
      - redis
    volumes:
      - nextcloud-apps:/var/www/html/apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
      - /ssdpool:/ssdpool # local external storage

  nc_db:
    image: mariadb
    restart: always
    hostname: nextcloud-db
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_USER_PW}

  redis:
    restart: always
    image: redis

  collabora:
    restart: always
    image: collabora/code
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - domain=${DOMAIN}

volumes:
  nextcloud-data:
  nextcloud-db:
  nextcloud-apps:
  nextcloud-config: