version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'git.numbers-labs.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gl_config:/etc/gitlab'
      - 'gl_logs:/var/log/gitlab'
      - 'gl_data:/var/opt/gitlab'
    shm_size: '256m'
    
volumes:
  gl_config:
  gl_logs:
  gl_data:
