version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab'
    volumes:
      - 'gl_config:/etc/gitlab'
      - 'gl_logs:/var/log/gitlab'
      - 'gl_data:/var/opt/gitlab'
    shm_size: '256m'
    
volumes:
  gl_config:
  gl_logs:
  gl_data:
